### PR TITLE
Add Tornado support

### PR DESCRIPTION
**Pull request by microdog**
This PR adds Tornado support. Tornado related code is located in `thrift_connector.tornado` package and tests are located at `tests/test_tornado.py`.

#### Implemented Clients

* TornadoThriftClient - Tornado client for native thrift library
* TornadoThriftPyClient - Tornado client for thriftpy library

#### Implemented Pools

* TornadoClientPool
* TornadoHeartbeatClientPool
* TornadoRandomMultiServerClient
* TornadoRoundRobinMultiServerClient

#### Tests

All of the tests(17/17) have been ported to Tornado related clients and pools, which is located at `tests/test_tornado.py`. No extra tests are added currently.

#### Examples

2 examples are added: `tornado_thrift_client.py` and `tornado_thriftpy_client.py`. Related scripts have been updated.

#### License

Class `_ContextManagerFuture` is based on the code from [toro](https://github.com/ajdavis/toro/blob/master/toro/__init__.py#L94-L128). The original code is licensed under Apache License, Version 2.0.

#### Usage

The use of Tornado pools is straight forward.

```python
service = thriftpy.load("pingpong_app/pingpong.thrift")
pool = TornadoClientPool(
    service.PingService,
    'localhost',
    8880,
    connection_class=TornadoThriftPyClient
)


def callback(future):
    print future.result()
    IOLoop.current().stop()


@gen.coroutine
def main():
    yield pool.ping()

    with (yield pool.connection_ctx()) as conn:
        yield conn.sleep(1)

    pool.win().add_done_callback(callback)


IOLoop.current().add_callback(main)
IOLoop.current().start()

```

### CODE REVIEW

**Comment by MrKiven** [comment]
looks great!

**Comment by microdog** [comment]
@MrKiven Still fixing the tests!

**Comment by microdog** [comment]
Green! 🍻

**Comment by wooparadog** [comment]
Thanks!

**Comment by microdog** [comment]
Any plan to release a new version?

**Pull request merged**
